# Generated by Django 5.2.13 on 2026-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('short_description', models.TextField(help_text='Shown on the grid')),
                ('content', models.TextField(help_text='Full case study')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('video_url', models.URLField(blank=True, help_text='Vimeo or YouTube link', null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
