# Generated by Django 5.2.9 on 2026-05-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLogo',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
