"""
Django settings for dma_agency project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^d**8vutb1+yb$4(mfg3mn=4dc!h9&x(&ynga_nq=-$o!dzpl*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'projects',
    'services',
    'contact',
    'site_core',
    'apps.site_pulse',
    'apps.site_atelier',
    'apps.site_orbit',
    'apps.site_signal',
    'apps.site_quiet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dma_agency.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'site_core.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'dma_agency.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Variant path prefixes (v9–v13) – formerly subdomain-based sites
VARIANT_PATHS = {
    "pulse":   "v9",
    "atelier": "v10",
    "orbit":   "v11",
    "signal":  "v12",
    "quiet":   "v13",
}

SITE_META = {
    "pulse": {
        "name": "Pulse",
        "tagline": "Loud creative for brands that refuse to whisper.",
        "accent": "#FF3B00",
    },
    "atelier": {
        "name": "Atelier",
        "tagline": "Considered storytelling for considered brands.",
        "accent": "#1A1A1A",
    },
    "orbit": {
        "name": "Orbit",
        "tagline": "Immersive worlds for brands that move forward.",
        "accent": "#7C5CFF",
    },
    "signal": {
        "name": "Signal",
        "tagline": "Glitch, gloss, and growth for digital-native brands.",
        "accent": "#FF00C8",
    },
    "quiet": {
        "name": "Quiet",
        "tagline": "Restraint is the loudest signal of confidence.",
        "accent": "#0F766E",
    },
}

# Canonical site origin (used for absolute URLs in sitemaps & OG tags).
CANONICAL_HOST = "localhost:8000"
CANONICAL_SCHEME = "http"
